# Generated by Django 6.0.3 on 2026-04-16 13:27

import django.db.models.deletion
import sigo_core.shared.upload_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Província')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=50, verbose_name='Documento')),
                ('orgao_emissor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Órgão Emissor')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Unidade')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('object_id', models.PositiveBigIntegerField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('arquivo', models.BinaryField(validators=[sigo_core.shared.upload_validators.validation_size], verbose_name='Arquivo')),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('hash_arquivo_atual', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigo_%(class)s_set', to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('object_id', models.PositiveBigIntegerField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('arquivo', models.BinaryField(validators=[sigo_core.shared.upload_validators.validation_size], verbose_name='Arquivo')),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('hash_arquivo_atual', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('tipo', models.CharField(choices=[('captura', 'Captura'), ('soltura', 'Soltura'), ('flora_antes', 'Flora Antes'), ('flora_depois', 'Flora Depois')], db_index=True, default='captura', max_length=20, verbose_name='Tipo da Foto')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigo_%(class)s_set', to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.BinaryField(blank=True, null=True, validators=[sigo_core.shared.upload_validators.validation_size], verbose_name='Foto')),
                ('foto_nome_arquivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do arquivo')),
                ('foto_mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('foto_tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='default', editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('unidade_ativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_ativas', to='sigo.unidade', verbose_name='Unidade ativa')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('object_id', models.PositiveBigIntegerField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('arquivo', models.BinaryField(validators=[sigo_core.shared.upload_validators.validation_size], verbose_name='Arquivo')),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('hash_arquivo_atual', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('hash_assinatura', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Hash da Assinatura')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigo_%(class)s_set', to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='sigo_assinatura_unique_objeto')],
            },
        ),
        migrations.CreateModel(
            name='Geolocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('object_id', models.PositiveBigIntegerField()),
                ('tipo', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Tipo da Geolocalização')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('hash_geolocalizacao', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigo_%(class)s_set', to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Geolocalização',
                'verbose_name_plural': 'Geolocalizações',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'tipo', 'latitude', 'longitude'), name='unique_geolocalizacao_por_objeto'), models.UniqueConstraint(condition=models.Q(('tipo__isnull', False)), fields=('content_type', 'object_id', 'tipo'), name='unique_geolocalizacao_tipo_por_objeto')],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('mensagem', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('alerta', 'Alerta'), ('erro', 'Erro')], db_index=True, default='info', max_length=20)),
                ('modulo', models.CharField(blank=True, choices=[('', 'Todos os módulos'), ('sigo', 'SIGO'), ('siop', 'SIOP'), ('sesmt', 'SESMT')], db_index=True, default='', max_length=20, verbose_name='Módulo alvo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='auth.group', verbose_name='Grupo alvo')),
                ('lidos_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL, verbose_name='Lidas por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='sigo.unidade', verbose_name='Unidade alvo')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['ativo', '-criado_em'], name='sigo_notifi_ativo_5dfd13_idx'), models.Index(fields=['modulo', 'ativo', '-criado_em'], name='sigo_notifi_modulo_8e27bf_idx')],
            },
        ),
    ]
