# Generated by Django 6.0.3 on 2026-03-29 23:04

import sigo_core.shared.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0002_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='foto_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME'),
        ),
        migrations.AddField(
            model_name='operador',
            name='foto_nome_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do arquivo'),
        ),
        migrations.AddField(
            model_name='operador',
            name='foto_tamanho',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto',
            field=models.BinaryField(blank=True, null=True, validators=[sigo_core.shared.upload_validators.validation_size], verbose_name='Foto'),
        ),
    ]
