# Generated by Django 6.0.3 on 2026-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0004_unidade_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
