# Generated by Django 6.0.3 on 2026-03-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sigo', '0005_unidade_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('mensagem', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('alerta', 'Alerta'), ('erro', 'Erro')], db_index=True, default='info', max_length=20)),
                ('modulo', models.CharField(blank=True, choices=[('', 'Todos os módulos'), ('sigo', 'SIGO'), ('siop', 'SIOP'), ('sesmt', 'SESMT')], db_index=True, default='', max_length=20, verbose_name='Módulo alvo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='auth.group', verbose_name='Grupo alvo')),
                ('lidos_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL, verbose_name='Lidas por')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='sigo.unidade', verbose_name='Unidade alvo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
