from django.urls import path

from .ocorrencias import (
    catalogo_areas,
    catalogo_locais_por_area,
    catalogo_naturezas,
    catalogo_tipos_ocorrencia,
    catalogo_tipos_pessoa,
    catalogo_tipos_por_natureza,
)
from .acesso_terceiros import (
    acesso_terceiros_edit,
    acesso_terceiros_export,
    acesso_terceiros_export_view_pdf,
    acesso_terceiros_index,
    acesso_terceiros_list,
    acesso_terceiros_new,
    acesso_terceiros_view,
    api_acesso_terceiros,
    api_acesso_terceiros_detail,
)
from .achados_perdidos import (
    api_achado_perdido_detail,
    api_achados_perdidos,
    achados_perdidos_edit,
    achados_perdidos_export,
    achados_perdidos_export_view_pdf,
    achados_perdidos_index,
    achados_perdidos_list,
    achados_perdidos_new,
    achados_perdidos_view,
)
from .acesso_colaboradores.views import (
    acesso_colaboradores_edit,
    acesso_colaboradores_export,
    acesso_colaboradores_export_view_pdf,
    acesso_colaboradores_index,
    acesso_colaboradores_list,
    acesso_colaboradores_new,
    acesso_colaboradores_view,
    api_acesso_colaboradores,
    api_acesso_colaboradores_detail,
)
from .controle_chaves.views import (
    api_controle_chaves,
    api_controle_chaves_detail,
    controle_chaves_edit,
    controle_chaves_export,
    controle_chaves_export_view_pdf,
    controle_chaves_index,
    controle_chaves_list,
    controle_chaves_new,
    controle_chaves_view,
)
from .controle_ativos.views import (
    api_controle_ativos,
    api_controle_ativos_detail,
    controle_ativos_edit,
    controle_ativos_export,
    controle_ativos_export_view_pdf,
    controle_ativos_index,
    controle_ativos_list,
    controle_ativos_new,
    controle_ativos_view,
)
from .crachas_provisorios.views import (
    api_crachas_provisorios,
    api_crachas_provisorios_detail,
    crachas_provisorios_edit,
    crachas_provisorios_export,
    crachas_provisorios_export_view_pdf,
    crachas_provisorios_index,
    crachas_provisorios_list,
    crachas_provisorios_new,
    crachas_provisorios_view,
)
from .efetivo.views import (
    api_efetivo,
    api_efetivo_detail,
    efetivo_edit,
    efetivo_export,
    efetivo_export_view_pdf,
    efetivo_index,
    efetivo_list,
    efetivo_new,
    efetivo_view,
)
from .liberacao_acesso.views import (
    api_liberacao_acesso,
    api_liberacao_acesso_detail,
    api_liberacao_acesso_chegada,
    liberacao_acesso_index,
    liberacao_acesso_list,
    liberacao_acesso_new,
    liberacao_acesso_view,
    liberacao_acesso_edit,
    liberacao_acesso_export,
    liberacao_acesso_export_view_pdf,
)
from .dashboard_views import home, notifications_list
from .download_views import anexo_download, assinatura_download, foto_download
from .ocorrencias import (
    api_ocorrencia_detail,
    api_ocorrencias,
    ocorrencias_edit,
    ocorrencias_export,
    ocorrencias_export_view_pdf,
    ocorrencias_index,
    ocorrencias_list,
    ocorrencias_new,
    ocorrencias_view,
)

app_name = 'siop'

urlpatterns = [
    path('', home, name='home'),
    path('notificacoes/', notifications_list, name='notifications_list'),
    path('api/catalogos/naturezas/', catalogo_naturezas, name='catalogo_naturezas'),
    path('api/catalogos/naturezas/tipos/', catalogo_tipos_por_natureza, name='catalogo_tipos_por_natureza'),
    path('api/catalogos/areas/', catalogo_areas, name='catalogo_areas'),
    path('api/catalogos/areas/locais/', catalogo_locais_por_area, name='catalogo_locais_por_area'),
    path('api/catalogos/tipos-pessoa/', catalogo_tipos_pessoa, name='catalogo_tipos_pessoa'),
    path('api/catalogos/tipos-ocorrencia/', catalogo_tipos_ocorrencia, name='catalogo_tipos_ocorrencia'),
    path('api/ocorrencias/', api_ocorrencias, name='api_ocorrencias'),
    path('api/ocorrencias/<int:pk>/', api_ocorrencia_detail, name='api_ocorrencia_detail'),
    path('api/acesso-terceiros/', api_acesso_terceiros, name='api_acesso_terceiros'),
    path('api/acesso-terceiros/<int:pk>/', api_acesso_terceiros_detail, name='api_acesso_terceiros_detail'),
    path('api/achados-perdidos/', api_achados_perdidos, name='api_achados_perdidos'),
    path('api/achados-perdidos/<int:pk>/', api_achado_perdido_detail, name='api_achado_perdido_detail'),
    path('api/acesso-colaboradores/', api_acesso_colaboradores, name='api_acesso_colaboradores'),
    path('api/acesso-colaboradores/<int:pk>/', api_acesso_colaboradores_detail, name='api_acesso_colaboradores_detail'),
    path('api/controle-chaves/', api_controle_chaves, name='api_controle_chaves'),
    path('api/controle-chaves/<int:pk>/', api_controle_chaves_detail, name='api_controle_chaves_detail'),
    path('api/controle-ativos/', api_controle_ativos, name='api_controle_ativos'),
    path('api/controle-ativos/<int:pk>/', api_controle_ativos_detail, name='api_controle_ativos_detail'),
    path('api/crachas-provisorios/', api_crachas_provisorios, name='api_crachas_provisorios'),
    path('api/crachas-provisorios/<int:pk>/', api_crachas_provisorios_detail, name='api_crachas_provisorios_detail'),
    path('api/efetivo/', api_efetivo, name='api_efetivo'),
    path('api/efetivo/<int:pk>/', api_efetivo_detail, name='api_efetivo_detail'),
    path('api/liberacao-acesso/', api_liberacao_acesso, name='api_liberacao_acesso'),
    path('api/liberacao-acesso/<int:pk>/', api_liberacao_acesso_detail, name='api_liberacao_acesso_detail'),
    path('api/liberacao-acesso/<int:pk>/chegada/', api_liberacao_acesso_chegada, name='api_liberacao_acesso_chegada'),
    path('ocorrencias/', ocorrencias_index, name='ocorrencias_index'),
    path('ocorrencias/lista/', ocorrencias_list, name='ocorrencias_list'),
    path('ocorrencias/nova/', ocorrencias_new, name='ocorrencias_new'),
    path('ocorrencias/exportar/', ocorrencias_export, name='ocorrencias_export'),
    path('ocorrencias/<int:pk>/export/pdf-view/', ocorrencias_export_view_pdf, name='ocorrencias_export_view_pdf'),
    path('ocorrencias/<int:pk>/', ocorrencias_view, name='ocorrencias_view'),
    path('ocorrencias/<int:pk>/editar/', ocorrencias_edit, name='ocorrencias_edit'),
    path('anexos/<int:pk>/download/', anexo_download, name='anexo_download'),
    path('fotos/<int:pk>/download/', foto_download, name='foto_download'),
    path('assinaturas/<int:pk>/download/', assinatura_download, name='assinatura_download'),
    path('acesso-terceiros/', acesso_terceiros_index, name='acesso_terceiros_index'),
    path('acesso-terceiros/lista/', acesso_terceiros_list, name='acesso_terceiros_list'),
    path('acesso-terceiros/novo/', acesso_terceiros_new, name='acesso_terceiros_new'),
    path('acesso-terceiros/exportar/', acesso_terceiros_export, name='acesso_terceiros_export'),
    path('acesso-terceiros/<int:pk>/export/pdf-view/', acesso_terceiros_export_view_pdf, name='acesso_terceiros_export_view_pdf'),
    path('acesso-terceiros/<int:pk>/', acesso_terceiros_view, name='acesso_terceiros_view'),
    path('acesso-terceiros/<int:pk>/editar/', acesso_terceiros_edit, name='acesso_terceiros_edit'),
    path('acesso-colaboradores/', acesso_colaboradores_index, name='acesso_colaboradores_index'),
    path('acesso-colaboradores/lista/', acesso_colaboradores_list, name='acesso_colaboradores_list'),
    path('acesso-colaboradores/novo/', acesso_colaboradores_new, name='acesso_colaboradores_new'),
    path('acesso-colaboradores/exportar/', acesso_colaboradores_export, name='acesso_colaboradores_export'),
    path('acesso-colaboradores/<int:pk>/export/pdf-view/', acesso_colaboradores_export_view_pdf, name='acesso_colaboradores_export_view_pdf'),
    path('acesso-colaboradores/<int:pk>/', acesso_colaboradores_view, name='acesso_colaboradores_view'),
    path('acesso-colaboradores/<int:pk>/editar/', acesso_colaboradores_edit, name='acesso_colaboradores_edit'),
    path('achados-perdidos/', achados_perdidos_index, name='achados_perdidos_index'),
    path('achados-perdidos/lista/', achados_perdidos_list, name='achados_perdidos_list'),
    path('achados-perdidos/novo/', achados_perdidos_new, name='achados_perdidos_new'),
    path('achados-perdidos/exportar/', achados_perdidos_export, name='achados_perdidos_export'),
    path('achados-perdidos/<int:pk>/export/pdf-view/', achados_perdidos_export_view_pdf, name='achados_perdidos_export_view_pdf'),
    path('achados-perdidos/<int:pk>/', achados_perdidos_view, name='achados_perdidos_view'),
    path('achados-perdidos/<int:pk>/editar/', achados_perdidos_edit, name='achados_perdidos_edit'),
    path('controle-chaves/', controle_chaves_index, name='controle_chaves_index'),
    path('controle-chaves/lista/', controle_chaves_list, name='controle_chaves_list'),
    path('controle-chaves/novo/', controle_chaves_new, name='controle_chaves_new'),
    path('controle-chaves/exportar/', controle_chaves_export, name='controle_chaves_export'),
    path('controle-chaves/<int:pk>/export/pdf-view/', controle_chaves_export_view_pdf, name='controle_chaves_export_view_pdf'),
    path('controle-chaves/<int:pk>/', controle_chaves_view, name='controle_chaves_view'),
    path('controle-chaves/<int:pk>/editar/', controle_chaves_edit, name='controle_chaves_edit'),
    path('controle-ativos/', controle_ativos_index, name='controle_ativos_index'),
    path('controle-ativos/lista/', controle_ativos_list, name='controle_ativos_list'),
    path('controle-ativos/novo/', controle_ativos_new, name='controle_ativos_new'),
    path('controle-ativos/exportar/', controle_ativos_export, name='controle_ativos_export'),
    path('controle-ativos/<int:pk>/export/pdf-view/', controle_ativos_export_view_pdf, name='controle_ativos_export_view_pdf'),
    path('controle-ativos/<int:pk>/', controle_ativos_view, name='controle_ativos_view'),
    path('controle-ativos/<int:pk>/editar/', controle_ativos_edit, name='controle_ativos_edit'),
    path('crachas-provisorios/', crachas_provisorios_index, name='crachas_provisorios_index'),
    path('crachas-provisorios/lista/', crachas_provisorios_list, name='crachas_provisorios_list'),
    path('crachas-provisorios/novo/', crachas_provisorios_new, name='crachas_provisorios_new'),
    path('crachas-provisorios/<int:pk>/export/pdf-view/', crachas_provisorios_export_view_pdf, name='crachas_provisorios_export_view_pdf'),
    path('crachas-provisorios/<int:pk>/', crachas_provisorios_view, name='crachas_provisorios_view'),
    path('crachas-provisorios/<int:pk>/editar/', crachas_provisorios_edit, name='crachas_provisorios_edit'),
    path('crachas-provisorios/exportar/', crachas_provisorios_export, name='crachas_provisorios_export'),
    path('efetivo/', efetivo_index, name='efetivo_index'),
    path('efetivo/lista/', efetivo_list, name='efetivo_list'),
    path('efetivo/novo/', efetivo_new, name='efetivo_new'),
    path('efetivo/exportar/', efetivo_export, name='efetivo_export'),
    path('efetivo/<int:pk>/export/pdf-view/', efetivo_export_view_pdf, name='efetivo_export_view_pdf'),
    path('efetivo/<int:pk>/', efetivo_view, name='efetivo_view'),
    path('efetivo/<int:pk>/editar/', efetivo_edit, name='efetivo_edit'),
    path('liberacao-acesso/', liberacao_acesso_index, name='liberacao_acesso_index'),
    path('liberacao-acesso/lista/', liberacao_acesso_list, name='liberacao_acesso_list'),
    path('liberacao-acesso/novo/', liberacao_acesso_new, name='liberacao_acesso_new'),
    path('liberacao-acesso/exportar/', liberacao_acesso_export, name='liberacao_acesso_export'),
    path('liberacao-acesso/<int:pk>/export/pdf-view/', liberacao_acesso_export_view_pdf, name='liberacao_acesso_export_view_pdf'),
    path('liberacao-acesso/<int:pk>/', liberacao_acesso_view, name='liberacao_acesso_view'),
    path('liberacao-acesso/<int:pk>/editar/', liberacao_acesso_edit, name='liberacao_acesso_edit'),
]
