from django.urls import path

from .views import (
    api_atendimento,
    api_atendimento_detail,
    api_atendimento_export,
    api_flora,
    api_flora_detail,
    api_flora_export,
    api_himenopteros,
    api_himenopteros_detail,
    api_himenopteros_export,
    api_manejo,
    api_manejo_detail,
    api_manejo_export,
    atendimento_export,
    atendimento_api_locais,
    atendimento_edit,
    atendimento_foto_view,
    atendimento_index,
    atendimento_list,
    atendimento_new,
    atendimento_assinatura_view,
    atendimento_view,
    atendimento_export_view_pdf,
    flora_export,
    flora_export_view_pdf,
    flora_foto_view,
    flora_index,
    flora_list,
    flora_new,
    flora_edit,
    flora_api_locais,
    flora_view,
    home,
    himenopteros_api_locais,
    himenopteros_edit,
    himenopteros_export,
    himenopteros_export_view_pdf,
    himenopteros_foto_view,
    himenopteros_index,
    himenopteros_list,
    himenopteros_new,
    himenopteros_view,
    manejo_export,
    manejo_export_view_pdf,
    manejo_api_especies,
    manejo_api_locais,
    manejo_edit,
    manejo_foto_view,
    manejo_index,
    manejo_list,
    manejo_new,
    notifications_list,
    manejo_view,
)

app_name = 'sesmt'

urlpatterns = [
    path('', home, name='home'),
    path('notificacoes/', notifications_list, name='notifications_list'),
    path('atendimento/', atendimento_index, name='atendimento_index'),
    path('atendimento/lista/', atendimento_list, name='atendimento_list'),
    path('atendimento/novo/', atendimento_new, name='atendimento_new'),
    path('atendimento/<int:pk>/editar/', atendimento_edit, name='atendimento_edit'),
    path('atendimento/<int:pk>/fotos/<int:foto_id>/', atendimento_foto_view, name='atendimento_foto_view'),
    path('atendimento/<int:pk>/assinaturas/<int:assinatura_id>/', atendimento_assinatura_view, name='atendimento_assinatura_view'),
    path('atendimento/exportar/', atendimento_export, name='atendimento_export'),
    path('atendimento/<int:pk>/export/pdf-view/', atendimento_export_view_pdf, name='atendimento_export_view_pdf'),
    path('atendimento/<int:pk>/', atendimento_view, name='atendimento_view'),
    path('atendimento/api/locais/', atendimento_api_locais, name='atendimento_api_locais'),
    path('api/atendimento/', api_atendimento, name='api_atendimento'),
    path('api/atendimento/export/', api_atendimento_export, name='api_atendimento_export'),
    path('api/atendimento/<int:pk>/', api_atendimento_detail, name='api_atendimento_detail'),
    path('manejo/', manejo_index, name='manejo_index'),
    path('manejo/lista/', manejo_list, name='manejo_list'),
    path('manejo/novo/', manejo_new, name='manejo_new'),
    path('manejo/<int:pk>/editar/', manejo_edit, name='manejo_edit'),
    path('manejo/<int:pk>/fotos/<int:foto_id>/', manejo_foto_view, name='manejo_foto_view'),
    path('manejo/exportar/', manejo_export, name='manejo_export'),
    path('manejo/<int:pk>/export/pdf-view/', manejo_export_view_pdf, name='manejo_export_view_pdf'),
    path('manejo/<int:pk>/', manejo_view, name='manejo_view'),
    path('manejo/api/locais/', manejo_api_locais, name='manejo_api_locais'),
    path('manejo/api/especies/', manejo_api_especies, name='manejo_api_especies'),
    path('api/manejo/', api_manejo, name='api_manejo'),
    path('api/manejo/export/', api_manejo_export, name='api_manejo_export'),
    path('api/manejo/<int:pk>/', api_manejo_detail, name='api_manejo_detail'),
    path('flora/', flora_index, name='flora_index'),
    path('flora/lista/', flora_list, name='flora_list'),
    path('flora/novo/', flora_new, name='flora_new'),
    path('flora/<int:pk>/editar/', flora_edit, name='flora_edit'),
    path('flora/<int:pk>/fotos/<int:foto_id>/', flora_foto_view, name='flora_foto_view'),
    path('flora/exportar/', flora_export, name='flora_export'),
    path('flora/<int:pk>/export/pdf-view/', flora_export_view_pdf, name='flora_export_view_pdf'),
    path('flora/<int:pk>/', flora_view, name='flora_view'),
    path('flora/api/locais/', flora_api_locais, name='flora_api_locais'),
    path('api/flora/', api_flora, name='api_flora'),
    path('api/flora/export/', api_flora_export, name='api_flora_export'),
    path('api/flora/<int:pk>/', api_flora_detail, name='api_flora_detail'),
    path('himenopteros/', himenopteros_index, name='himenopteros_index'),
    path('himenopteros/lista/', himenopteros_list, name='himenopteros_list'),
    path('himenopteros/novo/', himenopteros_new, name='himenopteros_new'),
    path('himenopteros/<int:pk>/editar/', himenopteros_edit, name='himenopteros_edit'),
    path('himenopteros/<int:pk>/fotos/<int:foto_id>/', himenopteros_foto_view, name='himenopteros_foto_view'),
    path('himenopteros/exportar/', himenopteros_export, name='himenopteros_export'),
    path('himenopteros/<int:pk>/export/pdf-view/', himenopteros_export_view_pdf, name='himenopteros_export_view_pdf'),
    path('himenopteros/<int:pk>/', himenopteros_view, name='himenopteros_view'),
    path('himenopteros/api/locais/', himenopteros_api_locais, name='himenopteros_api_locais'),
    path('api/himenopteros/', api_himenopteros, name='api_himenopteros'),
    path('api/himenopteros/export/', api_himenopteros_export, name='api_himenopteros_export'),
    path('api/himenopteros/<int:pk>/', api_himenopteros_detail, name='api_himenopteros_detail'),
]
