# Generated by Django 6.0.3 on 2026-03-29 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('tipo_pessoa', models.CharField(db_index=True, max_length=20, verbose_name='Tipo Pessoa')),
                ('data_ocorrencia', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Ocorrência')),
                ('natureza', models.CharField(db_index=True, max_length=50, verbose_name='Natureza')),
                ('tipo', models.CharField(db_index=True, max_length=50, verbose_name='Tipo')),
                ('area', models.CharField(db_index=True, max_length=50, verbose_name='Área')),
                ('local', models.CharField(db_index=True, max_length=50, verbose_name='Local')),
                ('cftv', models.BooleanField(default=False, verbose_name='Possui imagens CFTV?')),
                ('bombeiro_civil', models.BooleanField(db_index=True, default=False, verbose_name='Acionou BC?')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Ocorrência Finalizada?')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Ocorrência')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='AcessoTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('entrada', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Entrada')),
                ('saida', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e Hora da Saída')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa do Veículo')),
                ('p1', models.CharField(db_index=True, max_length=50, verbose_name='P1')),
                ('descricao_acesso', models.TextField(blank=True, verbose_name='Descrição de Acesso Terceiros')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_terceiros', to='sigo.pessoa')),
            ],
            options={
                'verbose_name': 'Acesso de Terceiros',
                'verbose_name_plural': 'Acessos de Terceiros',
                'ordering': ['-entrada', '-criado_em'],
                'indexes': [models.Index(fields=['pessoa', '-entrada'], name='siop_acesso_pessoa__1c5dd3_idx'), models.Index(fields=['p1', '-entrada'], name='siop_acesso_p1_76545b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('saida__isnull', True), ('saida__gte', models.F('entrada')), _connector='OR'), name='acesso_terceiros_saida_maior_ou_igual_entrada')],
            },
        ),
        migrations.CreateModel(
            name='AchadosPerdidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('tipo', models.CharField(db_index=True, max_length=50, verbose_name='Classificação do Item')),
                ('situacao', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Situação do Item')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
                ('local', models.CharField(db_index=True, max_length=30, verbose_name='Local do Achado/Perdido')),
                ('area', models.CharField(db_index=True, max_length=30, verbose_name='Área do Achado/Perdido')),
                ('organico', models.BooleanField(default=True, verbose_name='Orgânico?')),
                ('colaborador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colaborador Responsável')),
                ('setor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor do Colaborador')),
                ('data_devolucao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e Hora da Devolução')),
                ('ciop', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CIOP')),
                ('status', models.CharField(db_index=True, max_length=20, verbose_name='Status do Item')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa_achados_perdidos', to='sigo.pessoa', verbose_name='Pessoa Recebeu Item')),
            ],
            options={
                'verbose_name': 'Achado e Perdido',
                'verbose_name_plural': 'Achados e Perdidos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', '-criado_em'], name='siop_achado_tipo_48d2cc_idx'), models.Index(fields=['status', '-criado_em'], name='siop_achado_status_4e7e66_idx'), models.Index(fields=['area', 'local'], name='siop_achado_area_9d8f71_idx')],
            },
        ),
    ]
