# Generated by Django 6.0.3 on 2026-03-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_pessoa',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Tipo Pessoa'),
        ),
    ]
