# Generated by Django 6.0.3 on 2026-03-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0004_unidade_configuracaosistema'),
        ('siop', '0003_normalize_ocorrencia_catalog_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoterceiros',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos_terceiros', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='achadosperdidos',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achados_perdidos', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='sigo.unidade', verbose_name='Unidade'),
        ),
    ]
