# Generated by Django 6.0.3 on 2026-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0004_acessoterceiros_unidade_achadosperdidos_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoterceiros',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
        migrations.AddField(
            model_name='achadosperdidos',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
    ]
