# Generated by Django 6.0.3 on 2026-04-05 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0006_notificacao'),
        ('siop', '0005_acessoterceiros_unidade_sigla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('atendimento', models.CharField(max_length=255, verbose_name='Responsável Atendimento')),
                ('bilheteria', models.CharField(max_length=255, verbose_name='Responsável Bilheteria')),
                ('bombeiro_civil', models.CharField(max_length=255, verbose_name='Bombeiro Civil 1')),
                ('bombeiro_civil_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bombeiro Civil 2')),
                ('bombeiro_hidraulico', models.CharField(max_length=255, verbose_name='Bombeiro Hidráulico')),
                ('ciop', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CIOP')),
                ('eletrica', models.CharField(max_length=255, verbose_name='Responsável Elétrica')),
                ('artifice_civil', models.CharField(max_length=255, verbose_name='Responsável Artífice Civil')),
                ('ti', models.CharField(max_length=255, verbose_name='Responsável TI')),
                ('facilities', models.CharField(max_length=255, verbose_name='Responsável Facilities')),
                ('manutenção', models.CharField(max_length=255, verbose_name='Responsável Manutenção')),
                ('jardinagem', models.CharField(max_length=255, verbose_name='Responsável Jardinagem')),
                ('limpeza', models.CharField(max_length=255, verbose_name='Responsável Limpeza')),
                ('seguranca_trabalho', models.CharField(max_length=255, verbose_name='Responsável Segurança do Trabalho')),
                ('seguranca_patrimonial', models.CharField(max_length=255, verbose_name='Responsável Segurança Patrimonial')),
                ('meio_ambiente', models.CharField(max_length=255, verbose_name='Responsável Meio Ambiente')),
                ('engenharia', models.CharField(max_length=255, verbose_name='Responsável Engenharia')),
                ('estapar', models.CharField(max_length=255, verbose_name='Responsável Estapar')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrachaProvisorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('unidade_sigla', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade')),
                ('entrega', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Entrega')),
                ('devolucao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e Hora da Devolução')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento da Pessoa')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crachas_provisorios', to='sigo.pessoa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crachas_provisorios', to='sigo.unidade', verbose_name='Unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
