# Generated by Django 6.0.3 on 2026-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0009_controlechaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleefetivo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
