# Generated by Django 6.0.3 on 2026-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0010_controleefetivo_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleefetivo',
            name='plantao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Plantão'),
        ),
    ]
