# Generated by Django 6.0.3 on 2026-04-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0006_notificacao'),
        ('siop', '0011_controleefetivo_plantao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleefetivo',
            name='plantao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Responsável Plantão'),
        ),
        migrations.CreateModel(
            name='LiberacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('unidade_sigla', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento da Pessoa')),
                ('motivo', models.TextField(verbose_name='Motivo da Liberação de Acesso')),
                ('data_liberacao', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Liberação de Acesso')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('solicitante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitante')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_acesso', to='sigo.pessoa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_acesso', to='sigo.unidade', verbose_name='Unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
