# Generated by Django 6.0.3 on 2026-04-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0012_alter_controleefetivo_plantao_liberacaoacesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaoacesso',
            name='documento',
        ),
    ]
