# Generated by Django 6.0.3 on 2026-04-05 17:26

from django.db import migrations, models


def copy_liberacao_pessoa_to_pessoas(apps, schema_editor):
    LiberacaoAcesso = apps.get_model("siop", "LiberacaoAcesso")
    for liberacao in LiberacaoAcesso.objects.exclude(pessoa__isnull=True).iterator():
        liberacao.pessoas.add(liberacao.pessoa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0006_notificacao'),
        ('siop', '0013_remove_liberacaoacesso_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaoacesso',
            name='pessoas',
            field=models.ManyToManyField(related_name='liberacoes_acesso', to='sigo.pessoa', verbose_name='Pessoas'),
        ),
        migrations.RunPython(copy_liberacao_pessoa_to_pessoas, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='liberacaoacesso',
            name='pessoa',
        ),
    ]
