# Generated by Django 6.0.3 on 2026-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0014_remove_liberacaoacesso_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaoacesso',
            name='chegadas_registradas',
            field=models.JSONField(blank=True, default=list, verbose_name='Pessoas com chegada registrada'),
        ),
    ]
