# Generated by Django 6.0.3 on 2026-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0016_normalize_efetivo_and_ativos_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleefetivo',
            name='artifice_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Artífice Civil'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='atendimento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Atendimento'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='bilheteria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Bilheteria'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='bombeiro_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bombeiro Civil 1'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='bombeiro_hidraulico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bombeiro Hidráulico'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='eletrica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Elétrica'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='engenharia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Engenharia'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='estapar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Estapar'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='facilities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Facilities'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='jardinagem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Jardinagem'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='limpeza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Limpeza'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='manutencao',
            field=models.CharField(blank=True, db_column='manutenção', max_length=255, null=True, verbose_name='Responsável Manutenção'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='meio_ambiente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Meio Ambiente'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='seguranca_patrimonial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Segurança Patrimonial'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='seguranca_trabalho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Segurança do Trabalho'),
        ),
        migrations.AlterField(
            model_name='controleefetivo',
            name='ti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável TI'),
        ),
    ]
