# Generated by Django 6.0.3 on 2026-04-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigo', '0006_notificacao'),
        ('siop', '0017_alter_controleefetivo_artifice_civil_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('unidade_sigla', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade')),
                ('entrada', models.DateTimeField(db_index=True, verbose_name='Data e Hora da Entrada')),
                ('saida', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e Hora da Saída')),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa do Veículo')),
                ('p1', models.CharField(db_index=True, max_length=50, verbose_name='P1')),
                ('descricao_acesso', models.TextField(blank=True, verbose_name='Descrição de Acesso Colaboradores')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pessoa', models.ManyToManyField(related_name='acessos_colaboradores', to='sigo.pessoa')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acessos_colaboradores', to='sigo.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Acesso de Colaboradores',
                'verbose_name_plural': 'Acessos de Colaboradores',
                'ordering': ['-entrada', '-criado_em'],
                'indexes': [models.Index(fields=['p1', '-entrada'], name='siop_acesso_p1_44c603_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('saida__isnull', True), ('saida__gte', models.F('entrada')), _connector='OR'), name='acesso_colaboradores_saida_maior_ou_igual_entrada')],
            },
        ),
    ]
