"""Compatibilidade pública para as áreas operacionais do SIOP."""

from ..operacoes_views import (
    controle_ativos_edit,
    controle_ativos_export,
    controle_ativos_export_view_pdf,
    controle_ativos_index,
    controle_ativos_list,
    controle_ativos_new,
    controle_ativos_view,
    controle_chaves_edit,
    controle_chaves_export,
    controle_chaves_export_view_pdf,
    controle_chaves_index,
    controle_chaves_list,
    controle_chaves_new,
    controle_chaves_view,
    crachas_provisorios_edit,
    crachas_provisorios_export,
    crachas_provisorios_export_view_pdf,
    crachas_provisorios_index,
    crachas_provisorios_list,
    crachas_provisorios_new,
    crachas_provisorios_view,
    efetivo_edit,
    efetivo_export,
    efetivo_export_view_pdf,
    efetivo_index,
    efetivo_list,
    efetivo_new,
    efetivo_view,
    liberacao_acesso_edit,
    liberacao_acesso_export,
    liberacao_acesso_export_view_pdf,
    liberacao_acesso_index,
    liberacao_acesso_list,
    liberacao_acesso_new,
    liberacao_acesso_view,
)

__all__ = [name for name in globals() if not name.startswith("_")]
