# Generated by Django 6.0.3 on 2026-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('tipo_pessoa', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Pessoa')),
                ('area_atendimento', models.CharField(db_index=True, max_length=50, verbose_name='Área de Atendimento')),
                ('local', models.CharField(db_index=True, max_length=50, verbose_name='Local de Atendimento')),
                ('data_atendimento', models.DateTimeField(db_index=True, verbose_name='Data e Hora do Atendimento')),
                ('tipo_ocorrencia', models.CharField(db_index=True, max_length=50, verbose_name='Tipo de Ocorrência')),
                ('possui_acompanhante', models.BooleanField(default=False, verbose_name='Acompanhante?')),
                ('grau_parentesco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grau de Parentesco')),
                ('doenca_preexistente', models.BooleanField(default=False, verbose_name='Doença Preexistente?')),
                ('descricao_doenca', models.TextField(blank=True, null=True, verbose_name='Descrição da Doença')),
                ('alergia', models.BooleanField(default=False, verbose_name='Alergia?')),
                ('descricao_alergia', models.TextField(blank=True, null=True, verbose_name='Descrição da Alergia')),
                ('plano_saude', models.BooleanField(default=False, verbose_name='Possui Plano de Saúde?')),
                ('nome_plano_saude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Plano de Saúde')),
                ('numero_carteirinha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Carteirinha')),
                ('primeiros_socorros', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primeiros Socorros')),
                ('atendimentos', models.BooleanField(db_index=True, default=False, verbose_name='Atendimento Realizado?')),
                ('recusa_atendimento', models.BooleanField(default=False, verbose_name='Recusa de Atendimento?')),
                ('responsavel_atendimento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável pelo Atendimento')),
                ('seguiu_passeio', models.BooleanField(default=False, verbose_name='Seguiu para o Passeio?')),
                ('houve_remocao', models.BooleanField(default=False, verbose_name='Remoção?')),
                ('transporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporte Utilizado')),
                ('encaminhamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Encaminhamento')),
                ('hospital', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital')),
                ('medico_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médico Responsável')),
                ('crm', models.CharField(blank=True, max_length=100, null=True, verbose_name='CRM do Médico')),
                ('descricao', models.TextField(verbose_name='Descrição do Atendimento')),
                ('hash_atendimento', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Hash do Atendimento')),
            ],
            options={
                'verbose_name': 'Controle de Atendimento',
                'verbose_name_plural': 'Controles de Atendimento',
                'ordering': ['-data_atendimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('responsavel_registro', models.CharField(max_length=255, verbose_name='Responsável pelo Registro')),
                ('local', models.CharField(db_index=True, max_length=50, verbose_name='Localização')),
                ('area', models.CharField(db_index=True, max_length=50, verbose_name='Área')),
                ('popular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Popular')),
                ('especie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Espécie')),
                ('nativa', models.BooleanField(default=False, verbose_name='Nativa?')),
                ('estado_fitossanitario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Fitossanitário')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa para Registro')),
                ('acao_inicial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação Inicial')),
                ('acao_final', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ação Final')),
                ('data_hora_inicio', models.DateTimeField(db_index=True, verbose_name='Data e Hora do Registro')),
                ('data_hora_fim', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data e Hora do Término')),
                ('diametro_peito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro à Altura do Peito (cm)')),
                ('altura_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura Total (m)')),
                ('zona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Flora',
                'verbose_name_plural': 'Flora',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('data_hora', models.DateTimeField(db_index=True, verbose_name='Data e Hora do Manejo')),
                ('classe', models.CharField(db_index=True, max_length=25, verbose_name='Classe')),
                ('nome_cientifico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Científico')),
                ('nome_popular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Popular')),
                ('estagio_desenvolvimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estágio de Desenvolvimento')),
                ('area_captura', models.CharField(db_index=True, max_length=50, verbose_name='Área')),
                ('local_captura', models.CharField(db_index=True, max_length=50, verbose_name='Local')),
                ('descricao_local', models.TextField(blank=True, verbose_name='Descrição do Local')),
                ('importancia_medica', models.BooleanField(default=False, verbose_name='Importância Médica?')),
                ('realizado_manejo', models.BooleanField(db_index=True, default=False, verbose_name='Manejo Realizado?')),
                ('responsavel_manejo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável pelo Manejo')),
                ('area_soltura', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Área de Soltura')),
                ('local_soltura', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Local de Soltura')),
                ('descricao_local_soltura', models.TextField(blank=True, verbose_name='Descrição do Local de Soltura')),
                ('acionado_orgao_publico', models.BooleanField(default=False, verbose_name='Acionou Órgão Público?')),
                ('orgao_publico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Público')),
                ('numero_boletim_ocorrencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Boletim de Ocorrência')),
                ('motivo_acionamento', models.TextField(blank=True, verbose_name='Motivo do Acionamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Manejo',
                'verbose_name_plural': 'Manejos',
                'ordering': ['-data_hora', '-criado_em'],
            },
        ),
    ]
