# Generated by Django 6.0.3 on 2026-04-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesmt', '0001_initial'),
        ('sigo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controleatendimento',
            name='acompanhante_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_como_acompanhante', to='sigo.pessoa', verbose_name='Nome do Acompanhante'),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_atendimento', to='sigo.contato'),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_atendimento', to='sigo.pessoa'),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_atendimento', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='flora',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='flora',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='flora',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floras', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='himenoptero',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='himenoptero',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='himenoptero',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='himenopteros', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manejos', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='Testemunha',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sigo.pessoa')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sigo.contato')),
            ],
            options={
                'verbose_name': 'Testemunha',
                'verbose_name_plural': 'Testemunhas',
            },
            bases=('sigo.pessoa',),
        ),
        migrations.AddField(
            model_name='controleatendimento',
            name='testemunhas',
            field=models.ManyToManyField(blank=True, related_name='atendimentos_como_testemunha', to='sesmt.testemunha', verbose_name='Testemunhas'),
        ),
        migrations.AddIndex(
            model_name='flora',
            index=models.Index(fields=['area', 'local'], name='sesmt_flora_area_dffa77_idx'),
        ),
        migrations.AddIndex(
            model_name='flora',
            index=models.Index(fields=['especie', '-criado_em'], name='sesmt_flora_especie_b0371f_idx'),
        ),
        migrations.AddIndex(
            model_name='flora',
            index=models.Index(fields=['estado_fitossanitario', '-criado_em'], name='sesmt_flora_estado__63476e_idx'),
        ),
        migrations.AddIndex(
            model_name='himenoptero',
            index=models.Index(fields=['area', 'local'], name='sesmt_himen_area_73a925_idx'),
        ),
        migrations.AddIndex(
            model_name='himenoptero',
            index=models.Index(fields=['hipomenoptero', '-criado_em'], name='sesmt_himen_hipomen_8652f1_idx'),
        ),
        migrations.AddIndex(
            model_name='himenoptero',
            index=models.Index(fields=['classificacao_risco', '-criado_em'], name='sesmt_himen_classif_a01dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='manejo',
            index=models.Index(fields=['classe', '-data_hora'], name='sesmt_manej_classe_dc5969_idx'),
        ),
        migrations.AddIndex(
            model_name='manejo',
            index=models.Index(fields=['area_captura', '-data_hora'], name='sesmt_manej_area_ca_52723c_idx'),
        ),
        migrations.AddIndex(
            model_name='manejo',
            index=models.Index(fields=['local_captura', '-data_hora'], name='sesmt_manej_local_c_176eec_idx'),
        ),
        migrations.AddIndex(
            model_name='controleatendimento',
            index=models.Index(fields=['pessoa', '-data_atendimento'], name='sesmt_contr_pessoa__dd6c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='controleatendimento',
            index=models.Index(fields=['tipo_ocorrencia', '-data_atendimento'], name='sesmt_contr_tipo_oc_252b49_idx'),
        ),
        migrations.AddIndex(
            model_name='controleatendimento',
            index=models.Index(fields=['area_atendimento', '-data_atendimento'], name='sesmt_contr_area_at_c6576b_idx'),
        ),
    ]
