# Generated by Django 6.0.3 on 2026-03-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0002_initial'),
        ('sigo', '0004_unidade_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleatendimento',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles_atendimento', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='flora',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floras', to='sigo.unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manejos', to='sigo.unidade', verbose_name='Unidade'),
        ),
    ]
