# Generated by Django 6.0.3 on 2026-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesmt', '0003_controleatendimento_unidade_flora_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleatendimento',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
        migrations.AddField(
            model_name='flora',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='unidade_sigla',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Sigla da Unidade'),
        ),
    ]
